# Generated by Django 4.0.4 on 2023-04-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_biography_user_designation_user_lab_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='description',
        ),
        migrations.AddField(
            model_name='pictures',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
